version: '3'
services:
  backend:
    image: aws_s3_proxy_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    secrets:
      - backend_secrets
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app:rw
    ports:
      - "8000:8000"
    tty: true
    restart: always
  minio:
    image: docker.io/bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=alsofake
      - MINIO_ROOT_PASSWORD=alsofake
      - MINIO_DEFAULT_BUCKETS=s3-bucket-files

networks:
  default:
    external: true
    name: aws_s3_proxy_network

volumes:
  minio_data:
    driver: local

secrets:
  backend_secrets:
    file: ./backend_secrets.json